#!/bin/bash
# wine-bottle v. 0.2
# (c) 2009 Linux-Tipps.blogspot.com, (c) 2009 Joost @ http://home.student.utwente.nl/j.vanderhof
# newest version at http://linux-tipps.blogspot.com/2009/03/how-to-make-your-own-wine-bottles.html
# published under the GPL v. 3.0 http://gplv3.fsf.org/                                                                                                      

#Some changes by mirage335. Same license as above.

#Runs winecfg inside self-contained WINEPREFIX, in the same folder as this script. Intended for portable program installations.

. ubiquitous_bash.sh

wineBottle="$(getScriptAbsoluteFolder)/wineBottle"
mkdir -p "$wineBottle"
export WINEPREFIX="$wineBottle/"

winecfg
